### ISSUE TITLE
Analogous to otherLinks.displayIfNone for typingSnippets

### ISSUE THREAD

**Issue by AgentRBY** [zardoy/vscode-better-snippets#24]
Hello 👋

I have this `import` typing snippet:
```js
{
   "sequence": "import",
   "body": "import { $0 } from '$1'",
   "when":{
      "languages": [...],
      "locations": [ "lineStart" ],
      "otherLines": [
         {
            "line": -1,
            "testRegex": "import(\\s)?({|\\w)|^$",  // If prev line is `import {` or `import Word`, or empty line
            "displayIfNoLine": true
         }
      ]
   }
}
```
I check to see if the previous line is an import or an empty line. This works fine if there is a string before it, but if there is no string, the snippet doesn't work, even with displayIfNoLine
![Code_-_Insiders_pB0jiQLNYB](https://user-images.githubusercontent.com/68181944/201207056-852313ee-631e-4698-9b45-c826cc86bb28.gif)

**Comment by zardoy** [comment]
Sorry, I missed the priority of this issue somehow, and I must admit `otherLines` is one of the most not tested features of the extension (hope to fix it soon!).

> the snippet doesn't work

Not sure why, I'll look into it tomorrow.
I'm also thinking of renaming `displayIfNoLine` property to something else like `acceptIfOutsideFile`

**Comment by zardoy** [comment]
Hey, @AgentRBY just realized via repository search that `displayIfNoLine` was never implemented. I just pushed a lot of fixes & refactors to make `otherLines` finally stable, so in theory. Also remember that you can always use typing snippet with `fileStart` location.

I also added `skipEmptyLines` for your case:

```json
{
"sequence": "import",
            "body": "import { $0 } from '$1'",
            "when": {
                "locations": [
                    "lineStart"
                ],
                "otherLines": [
                    {
                        "line": -1,
                        "displayIfNoLine": true,
                        "skipEmptyLines": true,
                        "testRegex": "(^import(\\s)?({|\\w)$)|(^$)", // If prev line is `import {` or `import Word`, or empty line
                    }
                ]
            },
        },
```
