### ISSUE TITLE
Default value of `betterSnippets.languageSupesets` setting is empty

### ISSUE THREAD

**Issue by AgentRBY** [zardoy/vscode-better-snippets#25]
Hi 👋
I found a couple of issues with when.languages

1. In the absence of when.languages the snippet does not work anywhere. I would like it to be like the original snippets - that they would work everywhere, if the language is not specified

![Code_-_Insiders_CmmW0rJbCj](https://user-images.githubusercontent.com/68181944/201207835-9d0fdced-0175-4929-8c2f-ad4076a501d3.gif)

2. The [test snippets](https://github.com/zardoy/vscode-better-snippets/blob/main/test/snippets.jsonc#L15) say you can use `["react"]` and it will be an alias for `["javascriptreact", "typescriptreact"]`, but it doesn't work

![Code_-_Insiders_bXsC2EpTKw](https://user-images.githubusercontent.com/68181944/201208668-9dd9a071-832e-4fb4-8d75-29831c3ece67.gif)

3. Also Js specified in [built-in snippets](https://github.com/zardoy/vscode-better-snippets/blob/main/src/builtinSnippets.ts#L32) does not work (That's why these built-in snippets don't work at all)

![Code_-_Insiders_EIN2YTzhS2](https://user-images.githubusercontent.com/68181944/201209262-e717e1e1-ddd9-461b-9f61-0f71f246b8d5.gif)

**Comment by zardoy** [comment]
Hi! Thank you so much for the interest! You're right, language supersets should work as expected, however as I see from GIFs you actually don't get languages supersets suggestions while editing when.languages, there is something wrong with `betterSnippets.languageSupesets` setting (seems to be empty). This is really important, so I'll look at this when I wake up!

**Comment by zardoy** [comment]
> In the absence of when.languages the snippet does not work anywhere. I would like it to be like the original snippets - that they would work everywhere, if the language is not specified

Probably makes sense, I think you can use `["*"]` as value for now.
