### ISSUE TITLE
Typing snippets are inserted in incorrect Position

### ISSUE THREAD

**Issue by maIIady** [zardoy/vscode-better-snippets#28]
Since latest [vscode update](https://code.visualstudio.com/updates/v1_75)(and previously vscode-insiders) I started experiencing typing snippets are inserted in incorrect Position. (this even made me use default `vscode` as I just can't write code  without this extension now)
Example:

https://user-images.githubusercontent.com/74474615/216970854-62b7c236-35ed-4eb4-a99f-1dc26ff9596e.mp4

Didn't dive into it but looks like smth has changed with the `editor.insertSnippet()` behaviour. Gonna propose quick solution in a minute

**Comment by zardoy** [comment]
> this even made me use default vscode

What do you mean ?

**Comment by maIIady** [comment]
> > this even made me use default vscode
> 
> What do you mean ?

I mean this didn't reproduce in `vscode-stable` before [1.75](https://code.visualstudio.com/updates/v1_75), so I used it instead of `code-insiders` as correct work of your extension is essential for me. I mentioned it because I saw you are primarily using `code-insiders` on your machine, so you maybe already did some workarounds.
